#!/bin/bash

git add .
git status
echo "Is it all there? (Y/N): "
read -n 1 -s answer
if [ "$answer" == "y" ] || [ "$answer" == "Y" ]; then
	echo "Send custom commit msg? (Y/N)"
	read -n 1 -s msg_flag
	if [ "$msg_flag" == "y" ] || [ "$msg_flag" == "Y" ]; then
		echo "Enter message: "
		read message
		echo "Pushing commit: $message"
		git commit -m "$message"
		git push origin master
	else
		now=$(date +%d-%m-%Y)
		echo "Pushing commit: $now"
		git commit -m "$now"
		git push origin master
	fi
else
	echo "Nice try though"
	echo "See Ya!"
fi 
